name: Laravel ssdb test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSDB
        run: |
          cd /tmp
          wget --no-check-certificate https://github.com/ideawu/ssdb/archive/master.zip
          unzip master
          cd ssdb-master
          make
          sudo make install

      - name: Start SSDB
        env: 
          SSDB_PATH: "/usr/local/ssdb"
        run: |
          cd $SSDB_PATH
          sudo touch log.txt
          sudo chmod 777 log.txt
          sudo ./ssdb-server -d ssdb.conf

      - name: Test SSDB
        run: |
          ps aux|grep ssdb

      - name: Installing php
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
          extension-csv: mbstring, xdebug
          ini-values-csv: "post_max_size=256M, short_open_tag=On"

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check php extensions
        run: php -m

      - uses: actions/checkout@v1

      - name: Composer Install
        run: |
          composer install

      - name: PHPUnit Run
        run: |
          ./vendor/bin/phpunit --verbose

      # - name: Init webapp
      #   run: |
      #     cd $HOME
      #     composer create-project --prefer-dist laravel/laravel webapp

      # - name: Install laravel-ssdb
      #   run: |
      #     cd $HOME/webapp
      #     composer config repositories.laravel-ssdb path /home/runner/work/laravel-ssdb/*
      #     composer require "huangdijia/laravel-ssdb:*@dev" --prefer-dist
